---
name: Setup node for nx execution

inputs:
  token:
    type: string
    required: true

runs:
  using: composite
  steps:
    - uses: nrwl/nx-set-shas@v2
      name: Derive appropriate SHAs for base and head for `nx affected` commands
      with:
        main-branch-name: master

    - uses: actions/setup-node@v3
      name: Setup node
      with:
        node-version: 16
        cache: "npm"

    - name: Set npm auth token
      run: |
        npm set //npm.pkg.github.com/:_authToken ${{ inputs.token }}
      shell: bash

    - name: Install dependencies
      run: |
        npm ci
      shell: bash
